### ISSUE TITLE
wait for the breaking change in iced 0.13

### ISSUE THREAD

**Issue by Decodetalkers** [waycrate/exwlshelleventloop#32]

**Comment by sundaram123krishnan** [comment]
Hello there!
I have been using iced quit a lot nowadays, and my DE is hyprland. 
Maybe i can be of any help to this repository?
Thx

**Comment by Decodetalkers** [comment]
> Hello there! I have been using iced quit a lot nowadays, and my DE is hyprland. Maybe i can be of any help to this repository? Thx

Maybe you can  add a transparent bottom panel example to this repo. If it cannot be transparent, you can help take https://github.com/iced-rs/iced/pull/484/ as example.. 

the flow of iced_layershell is totally a miss.. but i do not have better idea to make a better flow..

and I want to make a iced virtual-keyboard project.. maybe you can help. not the project of virtual keyboard is not made with iced but cairo..

and we need to impl the text-input-v3 for layershellev..

**Comment by Decodetalkers** [comment]
Finished.. but ime is still not merged in upstream iced
