### ISSUE TITLE
Performance issue on Hyprland

### ISSUE THREAD

**Issue by lacarthur** [waycrate/exwlshelleventloop#7]
Hi, the following program :
```rust
use iced::{executor, widget::text, Command, Theme};
use iced_layershell::{
    Application,
    settings::{Settings, LayerShellSettings},
};

struct BarExample;

impl Application for BarExample {
    type Executor = executor::Default;

    type Message = ();

    type Theme = Theme;

    type Flags = ();

    fn new(_flags: Self::Flags) -> (Self, iced::Command<Self::Message>) {
        (Self, Command::none())
    }

    fn namespace(&self) -> String {
        "BarExample".into()
    }

    fn update(&mut self, _message: Self::Message) -> iced::Command<Self::Message> {
        Command::none()
    }

    fn view(&self) -> iced::Element<'_, Self::Message, Self::Theme, iced::Renderer> {
        text("hi").into()
    }
}

fn main() -> Result<(), iced_layershell::Error> {
    BarExample::run(Settings {
        layer_settings: LayerShellSettings {
            size: Some((1356, 30)),
            ..Default::default()
        },
        ..Default::default()
    })
}
```
results in a 15% cpu usage on Hyprland. It also makes Hyprland use ~75x more cpu time than usual.
I created a flamegraph :
![flamegraph](https://github.com/waycrate/exwlshelleventloop/assets/108178953/a7cab267-fd50-4732-b663-e65f5e4f948c)
and it looks like most of the time is spent in the function `wayland_client::event_queue::EventQueue<State>::roundtrip`.

I'm using `iced` version 0.12.1, and `iced_layershell` version 0.2.2, and Hyprland version 0.39.1

**Comment by Decodetalkers** [comment]
https://github.com/waycrate/exwlshelleventloop/blob/master/layershellev/src/lib.rs#L1639


I think it is because this part. let me think if blocking_dispatch can fix it..

**Comment by Decodetalkers** [comment]
can you try git version for a test? I think I have fixed it

**Comment by lacarthur** [comment]
Hey, I tried the new version and it seems to be working. I'm now at less than .1% cpu usage :)
Thank you very much!

**Comment by Decodetalkers** [comment]
but this fix make it hard to handle long pressed keyboard event.. Emm..

**Comment by Decodetalkers** [comment]
I think my fix is wrong.. if use blocking_dispatch. if the data of the surface is updated. only when you do something to the program , it update the surface.. I will looking for other ways to fix it

**Comment by Decodetalkers** [comment]
Can you try https://github.com/waycrate/exwlshelleventloop/pull/8 this pull request? I try to control the time to refresh the data. maybe it will make it better

**Comment by lacarthur** [comment]
I tried it and it goes back to the original issue, too much cpu usage.

**Comment by Decodetalkers** [comment]
Emm. I have a better Idea to fix it. now please help me try that again. I use sctk to handle it now

**Comment by Decodetalkers** [comment]
@lacarthur Yes, I think after use event_loop, it is finally fixed

**Comment by lacarthur** [comment]
It does seem to work, yeah. Hyprland is back to regular cpu usage, and the example program runs at about ~3% cpu usage. It's still more than what I would expect of such a program, but this specific issue seems to be fixed.

**Comment by Decodetalkers** [comment]
ok. I will make a new release now. do you have interested to help me finish other unfinished part?

**Comment by lacarthur** [comment]
Hi, thanks for dealing with the issue so swiftly. Unfortunately, I don't really have the time to help out with the development. Best of luck though
