### ISSUE TITLE
Ability to listen on surface Unfocus events

### ISSUE THREAD

**Issue by Exidex** [waycrate/exwlshelleventloop#98]
PopOS's Iced fork has an ability to listen on unfocus events, e.g. clicking outside of surface, which is useful for application launcher-like applications 

See implementation in PopOS's fork: https://github.com/pop-os/iced/blob/5a3803923ee13388ef8638675f237998443aa45c/winit/src/platform_specific/wayland/sctk_event.rs#L460-L470

**Comment by Decodetalkers** [comment]
I have already handle the Unfocus event now.. Emm

**Comment by Exidex** [comment]
Great! Thanks for doing it so fast
