### ISSUE TITLE
Unable to remove main window in multi window Application

### ISSUE THREAD

**Issue by Exidex** [waycrate/exwlshelleventloop#99]
In multi_window Application it is not currently possible to remove main window. Main window seems to have id 0 if start mode is background [code](https://github.com/waycrate/exwlshelleventloop/blob/a08d67619fc7aebeee0408d36be2e0d3561ede3d/layershellev/src/lib.rs#L749) or is otherwise random. In iced 0.13 window::Id::MAIN was removed in favor of always specifying id for new windows. And window::Id::unique() starts at 1. Additionally in daemon mode (new multi_window replacement) application starts without any windows. Also there is no way to get an id of a window in iced_layershell, which is possible in iced 0.13

**Comment by Decodetalkers** [comment]
I do not quite know how to fix it... because seems the main wl_surface cannot be destroyed then the iced compositor will also been destroyed.. a bit hard for me.. what is the usecase?

**Comment by Exidex** [comment]
@Decodetalkers thanks for such fast changes

The use case is showing and hiding window of application launcher. Application is usually started without the main window when DE/WM starts and then window is shown by pressing global shortcut.

I have been testing your changes which added `iced_layershell::build_pattern::daemon` and it seems to work ok with no windows. 

But I am facing a unwrap panic here, when removing a window
https://github.com/waycrate/exwlshelleventloop/blob/8e5bc54f97588e10033b165e0837c2e71a8fbe79/iced_layershell/src/multi_window.rs#L400

Also, possibly unrelated, for some reason the created window is fully transparent with nothing being rendered, not quite sure if it a problem on my side. here is a migration to iced-layershell commit if you want to take a look: https://github.com/project-gauntlet/gauntlet/commit/9a57c47dbeeadcbf91f0285d65169e7112e9660c

**Comment by Decodetalkers** [comment]
> @Decodetalkers thanks for such fast changes
> 
> The use case is showing and hiding window of application launcher. Application is usually started without the main window when DE/WM starts and then window is shown by pressing global shortcut.
> 
> I have been testing your changes which added `iced_layershell::build_pattern::daemon` and it seems to work ok with no windows.
> 
> But I am facing a unwrap panic here, when removing a window
> 
> https://github.com/waycrate/exwlshelleventloop/blob/8e5bc54f97588e10033b165e0837c2e71a8fbe79/iced_layershell/src/multi_window.rs#L400
> 
> ~Also, possibly unrelated, for some reason the created window only shows background color with nothing being rendered, not quite sure if it a problem on my side. here is a migration to iced-layershell commit if you want to take a look: [project-gauntlet/gauntlet@9a57c47](https://github.com/project-gauntlet/gauntlet/commit/9a57c47dbeeadcbf91f0285d65169e7112e9660c)~
> 
> Found the issue, the window id specified with `LayershellCustomActionsWithInfo::NewLayerShell` does not match the window id passed to daemon's view function. If window is created with id == 1, id == 2 will be passed to view function

The problem is that we cannot know the main id.. and for iced_layershell, the main id may be more than one. Then this time we cannot know if the id is the main window. Possible solution is to send close request from the widget in view, where they know the id

**Comment by Decodetalkers** [comment]
https://github.com/waycrate/exwlshelleventloop/pull/101 please try this pr. now I add the ability to record the mainwindow ids, now it is possible for you to know the id of mainwindow

**Comment by Decodetalkers** [comment]
> In multi_window Application it is not currently possible to remove main window. Main window seems to have id 0 if start mode is background [code](https://github.com/waycrate/exwlshelleventloop/blob/a08d67619fc7aebeee0408d36be2e0d3561ede3d/layershellev/src/lib.rs#L749) or is otherwise random. In iced 0.13 window::Id::MAIN was removed in favor of always specifying id for new windows. And window::Id::unique() starts at 1. Additionally in daemon mode (new multi_window replacement) application starts without any windows. Also there is no way to get an id of a window in iced_layershell, which is possible in iced 0.13

by the way, how can iced get the mainwindow id?

**Comment by Exidex** [comment]
> please try this pr

I am not quite sure how I would need use that 

> by the way, how can iced get the mainwindow id?

Basically this is the difference between `iced::daemon` and `iced::application`

If you are using `iced::application` it means you will always have at least one window, if you close the last window whole program exits. All functions (title, update, view) passed to `iced::application` do not have id parameters because you will never need it for simple applications. But you can still get the id using `get_oldest` and `get_latest` task actions.

When using `iced::daemon` application starts without any windows and does not exit when there is no windows left. You can use `window::open` to create new window, this function returns `(Id, Task<Id>)` and you can store the Id it returns. Additionally all functions (title, update, view) passed to `iced::daemon` have `window::Id` parameter which allows to have different behavior depending on window (including different titles per window)

**Comment by Exidex** [comment]
Either way, it is already possible to get window id with `iced_layershell::build_pattern::daemon`. 

I just need you to fix:
- Panic when removing a window
- Fix window id that is passed to `view` function so it will match the window id passed into NewLayerShell action
- Add window id to `daemon` NameSpace function

**Comment by Decodetalkers** [comment]
> Either way, it is already possible to get window id with `iced_layershell::build_pattern::daemon`. 
> 
> I just need you to fix:
> - Panic when removing a window
> - Fix window id that is passed to `view` function so it will match the window id passed into NewLayerShell action
> - Add window id to `daemon` NameSpace function

Emm.

If you meet removing window panic, that means you have passed an id does not exist

I think that NewLayerShell won't accept any id, you can only receive the id by registering the function of set_id_info, and use the info to find the id, and also you need to listen on remove_id function

Why is it needed to pass id to the namespace function?

**Comment by Decodetalkers** [comment]
And that pr allows you to mark one field of the enum to accept the creating and removing event of main windows. I think that will meet your needs. The only thing you need to do is just register the set_id_info and remove_id

**Comment by Decodetalkers** [comment]
Haa... I see.. that LayershellCustomActionsWithId, this id means the id of the sender, not the id to be created... sorry for that, you had better to use the macro to impl it will be better..

**Comment by Exidex** [comment]
Ok, I see.

The problem is that the api style doesn't match to usual iced. It is needlessly complicated to have callback-style api to get id of the windows. Why would I need to implement all id_info, set_id_info and remove_id_info if i could just pass my id to the create new layer message and store it my self (like already implemented in https://github.com/project-gauntlet/gauntlet/commit/9a57c47dbeeadcbf91f0285d65169e7112e9660c) it is a lot less code and it is how it is done in usual iced and in PopOS's fork with layer shell

> Why is it needed to pass id to the namespace function?

same reason why there is id in `iced::deamon` title. to have different namespace based on which window it is for

**Comment by Decodetalkers** [comment]
> Ok, I see.
> 
> The problem is that the api style doesn't match to usual iced. It is needlessly complicated to have callback-style api to get id of the windows. Why would I need to implement all id_info, set_id_info and remove_id_info if i could just pass my id to the create new layer message and store it my self (like already implemented in https://github.com/project-gauntlet/gauntlet/commit/9a57c47dbeeadcbf91f0285d65169e7112e9660c) it is a lot less code and it is how it is done in usual iced and in PopOS's fork with layer shell
> 
> > Why is it needed to pass id to the namespace function?
> 
> same reason why there is id in `iced::deamon` title. to have different namespace based on which window it is for
> 
> 

Namespace is not a title, it is just used to tell wm what this program is. And a program just owned one namespace.

Because we need to mark different layershell, get their identity. You can take a look at that example

**Comment by Decodetalkers** [comment]
> Ok, I see.
> 
> The problem is that the api style doesn't match to usual iced. It is needlessly complicated to have callback-style api to get id of the windows. Why would I need to implement all id_info, set_id_info and remove_id_info if i could just pass my id to the create new layer message and store it my self (like already implemented in [project-gauntlet/gauntlet@9a57c47](https://github.com/project-gauntlet/gauntlet/commit/9a57c47dbeeadcbf91f0285d65169e7112e9660c)) it is a lot less code and it is how it is done in usual iced and in PopOS's fork with layer shell
> 
> > Why is it needed to pass id to the namespace function?
> 
> same reason why there is id in `iced::deamon` title. to have different namespace based on which window it is for

Ha.. I have already understand your problem.. 

the window::open in iced return the `window::Action::Open`, which I cannot add mine part for it. my lib can just send the Messages, .. and .. Yes, I can use the id of the sender to create the layershell, instead use the window::Id::unique to create one.. you are right. then it will be a little vague for the usage of the id.. it can be the sender, or the id of the new layershell..

For another thing about why I create the WindowInfo.. because the layershell is not created just after the messaged be sended, sometimes maybe with multi times of clicked, it will create more than once layershell, so it need to be controlled in some enum, so I create the WindowInfo.. 

Above all, I will create a pr for it.. then you can take a try

**Comment by Decodetalkers** [comment]
Emm.. wait for a minitue.. I think just keep the id be the sender will be better.. next time I will allow the windowinfo just be the Id, add something like  simple_daemon

The Id should keep be the sender will be better, because I have found that NewMenu and NewPopUp also need the sender to find their position..

**Comment by Decodetalkers** [comment]
Ok, after thinking about this thing... this design is a mistake.. but now I do not have enough energy to change it ..

**Comment by Decodetalkers** [comment]
done https://github.com/waycrate/exwlshelleventloop/pull/103

**Comment by Decodetalkers** [comment]
done, now you can try the new rc version.. I think that will solve your problem

**Comment by Exidex** [comment]
Works now as intended, thanks a lot!
